apiVersion: v1
kind: Service
metadata:
  labels:
    app: blizzard-demo
  name: blizzard-demo
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 32222
  selector:
    app: blizzard-demo
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blizzard-demo
  name: blizzard-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blizzard-demo
  template:
    metadata:
      labels:
        app: blizzard-demo
    spec:
      containers:
      - name: blizzard-demo
        image: 152493160469.dkr.ecr.us-east-1.amazonaws.com/ecr-blizzard-ue1:1.0.1
        ports:
        - containerPort: 5000