apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: blizzard-demo
  name: blizzard-demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: blizzard-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blizzard-demo
    spec:
      containers:
      - image: 152493160469.dkr.ecr.us-east-1.amazonaws.com/ecr-blizz-ue1:1.0.1
        name: blizzard-demo
        ports:
        - containerPort: 5000
        resources: {}
status: {}