{{- if .Values.externalSecret }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}-secret
spec:
  backendType: secretsManager
  dataFrom:
    - {{ .Values.externalSecret }}
{{- end }}
