apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: blizzard-demo
    app.kubernetes.io/managed-by: Helm
  name: blizzard-demo
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 32222
  selector:
    app: blizzard-demo
  type: NodePort
status:
  loadBalancer: {}
