{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.servicePort }}
      targetPort: {{ .Values.service.servicePort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.name }}
{{- end }}
